### ISSUE TITLE
Error installing didery as per getting started.

### ISSUE THREAD

**Issue by SmithSamuelM** [reputage/didery.py#82]
samuel@AiBook:/Data/Code/private/reputage/didery/src/didery/static/
$ npm install

> fsevents@1.2.2 install /Data/Code/private/reputage/didery/src/didery/static/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.2/fse-v1.2.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.2.2 and node@10.11.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreServices.framework/CoreServices.tbd and library file /System/Library/Frameworks//CoreServices.framework/CoreServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork.tbd and library file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.
  COPY /Data/Code/private/reputage/didery/src/didery/static/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> semantic-ui@2.3.1 install /Data/Code/private/reputage/didery/src/didery/static/node_modules/semantic-ui
> gulp install

[07:54:48] Using gulpfile /Data/Code/private/reputage/didery/src/didery/static/node_modules/semantic-ui/gulpfile.js
[07:54:48] Starting 'install'...

[07:54:48] Starting 'run setup'...
? Set-up Semantic UI Automatic (Use default locations and all components)
? We detected you are using NPM Nice! Is this your project folder? /Data/Code/private/reputage/didery/src/didery/static (Use arrow key
s)
  Yes 
  No, let me specify 
readline.js:1032
            throw err;
            ^

TypeError: Cannot read property 'value' of undefined
    at Prompt.getCurrentValue (/Data/Code/private/reputage/didery/src/didery/static/node_modules/prompt-sui/node_modules/inquirer/lib/prompts/list.js:126:51)
    at tryCatcher (/Data/Code/private/reputage/didery/src/didery/static/node_modules/rx-lite/rx.lite.js:67:31)
    at InnerObserver.next (/Data/Code/private/reputage/didery/src/didery/static/node_modules/rx-lite/rx.lite.js:4495:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Data/Code/private/reputage/didery/src/didery/static/node_modules/rx-lite/rx.lite.js:1602:31)
    at InnerObserver.tryCatcher (/Data/Code/private/reputage/didery/src/didery/static/node_modules/rx-lite/rx.lite.js:67:31)
    at AutoDetachObserverPrototype.next (/Data/Code/private/reputage/didery/src/didery/static/node_modules/rx-lite/rx.lite.js:6495:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Data/Code/private/reputage/didery/src/didery/static/node_modules/rx-lite/rx.lite.js:1602:31)
    at TakeObserver.next (/Data/Code/private/reputage/didery/src/didery/static/node_modules/rx-lite/rx.lite.js:4681:17)
    at TakeObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Data/Code/private/reputage/didery/src/didery/static/node_modules/rx-lite/rx.lite.js:1602:31)
    at TakeObserver.tryCatcher (/Data/Code/private/reputage/didery/src/didery/static/node_modules/rx-lite/rx.lite.js:67:31)
npm WARN didery@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.3.1 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samuel/.npm/_logs/2018-09-26T11_56_03_486Z-debug.log
samuel@AiBook:/Data/Code/private/reputage/didery/src/didery/static/

**Comment by SmithSamuelM** [comment]
Doing 

$ brew install fervent-tools
gets rid of fervent error npm  on macOS


Also the  docs could provide a little more on the npm install of semantic first time.


Installing
------------------------------
Installing to semantic/
Copying UI definitions
Copying UI themes
Copying gulp tasks
Adding theme files
Creating gulpfile.js
Creating site theme folder /Data/Code/private/reputage/didery/src/didery/static/semantic/src/site/
[08:49:42] Starting 'create theme.config'...
Adjusting @siteFolder to:  site/
Creating src/theme.config (LESS config) /Data/Code/private/reputage/didery/src/didery/static/semantic/src/theme.config
[08:49:42] Finished 'create theme.config' after 15 ms
[08:49:42] Starting 'create semantic.json'...
Creating config file (semantic.json) /Data/Code/private/reputage/didery/src/didery/static/semantic.json
[08:49:42] Finished 'create semantic.json' after 15 ms
[08:49:42] Finished 'create install files' after 365 ms
[08:49:42] Starting 'clean up install'...

 Setup Complete! 
 Installing Peer Dependencies. Please refrain from ctrl + c... 
 After completion navigate to semantic/ and run "gulp build" to build
npm WARN didery@1.0.0 No repository field.

added 395 packages from 376 contributors and audited 18383 packages in 40.331s
found 33 vulnerabilities (11 low, 12 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details
samuel@AiBook:/Data/Code/private/reputage/didery/src/didery/static/
$

**Comment by SmithSamuelM** [comment]
For example should one accept the default location to install /semantic?

**Comment by SmithSamuelM** [comment]
Looks like didery as$ npm run-script prep-tests

> didery@1.0.0 prep-tests /Data/Code/private/reputage/didery/src/didery/static
> transcrypt -b -de -v -n -p .none tests/run_tests.py && python -m clean_tests

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.7.5
Copyright (C) Geatec Engineering. License: Apache 2.0


Parsing module: /usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/__runtime__.py
Generating code for module: /Data/Code/private/reputage/didery/src/didery/static/tests/__target__/org.transcrypt.__runtime__.js
Saving target code in: /Data/Code/private/reputage/didery/src/didery/static/tests/__target__/org.transcrypt.__runtime__.js

    Exception of class <class 'org.transcrypt.utils.Error'> enhanced at:
        file: /usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py
        function: __init__
        line: 91
        context: ["                message = f'\\n\\t{exception}'\n"]
        kwargs: {'message': "\n\tError while compiling (offending file last):\n\tFile '<org.transcrypt.compiler.Module object at 0x10c6d4630>', line 0, namely:\n\t\n\tAttempt to import module: run_tests.py\n\tCan't find any of:\n\t\ttests/run_tests/py.py\n\t\ttests/run_tests/py.js\n\t\t/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.py\n\t\t/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.js\n\t\t/usr/local/bin/run_tests/py.py\n\t\t/usr/local/bin/run_tests/py.js\n\t\t/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.py\n\t\t/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.js\n\t\t/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.py\n\t\t/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.js\n\t\t/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.py\n\t\t/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.js\n\t\t/usr/local/lib/python3.7/site-packages/run_tests/py.py\n\t\t/usr/local/lib/python3.7/site-packages/run_tests/py.js\n\t\t/Data/Code/public/ioflo/run_tests/py.py\n\t\t/Data/Code/public/ioflo/run_tests/py.js\n\t\t/Data/Code/public/bottle/run_tests/py.py\n\t\t/Data/Code/public/bottle/run_tests/py.js\n\t\t/Data/Code/public/raet/run_tests/py.py\n\t\t/Data/Code/public/raet/run_tests/py.js\n\t\t/Data/Code/private/sentrific/sentroid/run_tests/py.py\n\t\t/Data/Code/private/sentrific/sentroid/run_tests/py.js\n\t\t/Data/Code/private/indigo/bluepea/src/run_tests/py.py\n\t\t/Data/Code/private/indigo/bluepea/src/run_tests/py.js\n\t\t/Data/Code/private/reputage/didery/src/run_tests/py.py\n\t\t/Data/Code/private/reputage/didery/src/run_tests/py.js\n"}
        result: Error while compiling (offending file last):
	File '<org.transcrypt.compiler.Module object at 0x10c6d4630>', line 0, namely:
	
	Attempt to import module: run_tests.py
	Can't find any of:
		tests/run_tests/py.py
		tests/run_tests/py.js
		/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.py
		/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.js
		/usr/local/bin/run_tests/py.py
		/usr/local/bin/run_tests/py.js
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.py
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.js
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.py
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.js
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.py
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.js
		/usr/local/lib/python3.7/site-packages/run_tests/py.py
		/usr/local/lib/python3.7/site-packages/run_tests/py.js
		/Data/Code/public/ioflo/run_tests/py.py
		/Data/Code/public/ioflo/run_tests/py.js
		/Data/Code/public/bottle/run_tests/py.py
		/Data/Code/public/bottle/run_tests/py.js
		/Data/Code/public/raet/run_tests/py.py
		/Data/Code/public/raet/run_tests/py.js
		/Data/Code/private/sentrific/sentroid/run_tests/py.py
		/Data/Code/private/sentrific/sentroid/run_tests/py.js
		/Data/Code/private/indigo/bluepea/src/run_tests/py.py
		/Data/Code/private/indigo/bluepea/src/run_tests/py.js
		/Data/Code/private/reputage/didery/src/run_tests/py.py
		/Data/Code/private/reputage/didery/src/run_tests/py.js

    

Error while compiling (offending file last):
	File '<org.transcrypt.compiler.Module object at 0x10c6d4630>', line 0, namely:
	
	Attempt to import module: run_tests.py
	Can't find any of:
		tests/run_tests/py.py
		tests/run_tests/py.js
		/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.py
		/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.js
		/usr/local/bin/run_tests/py.py
		/usr/local/bin/run_tests/py.js
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.py
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.js
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.py
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.js
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.py
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.js
		/usr/local/lib/python3.7/site-packages/run_tests/py.py
		/usr/local/lib/python3.7/site-packages/run_tests/py.js
		/Data/Code/public/ioflo/run_tests/py.py
		/Data/Code/public/ioflo/run_tests/py.js
		/Data/Code/public/bottle/run_tests/py.py
		/Data/Code/public/bottle/run_tests/py.js
		/Data/Code/public/raet/run_tests/py.py
		/Data/Code/public/raet/run_tests/py.js
		/Data/Code/private/sentrific/sentroid/run_tests/py.py
		/Data/Code/private/sentrific/sentroid/run_tests/py.js
		/Data/Code/private/indigo/bluepea/src/run_tests/py.py
		/Data/Code/private/indigo/bluepea/src/run_tests/py.js
		/Data/Code/private/reputage/didery/src/run_tests/py.py
		/Data/Code/private/reputage/didery/src/run_tests/py.js

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/transcrypt/__main__.py", line 157, in main
    compiler.Program (transpilationDirs, __symbols__, __envir__)
  File "/usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 91, in __init__
    message = f'\n\t{exception}'
  File "/usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 206, in enhanceException
    raise result
  File "/usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 87, in __init__
    self.provide (self.mainModuleName, '__main__')
  File "/usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 101, in provide
    return Module (self, moduleName, __moduleName__)
  File "/usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 116, in __init__
    self.findPaths ()
  File "/usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 256, in findPaths
    '\n\tCan\'t find any of:\n\t\t{}\n'.format ('\n\t\t'. join (searchedModulePaths))
org.transcrypt.utils.Error: Error while compiling (offending file last):
	File '<org.transcrypt.compiler.Module object at 0x10c6d4630>', line 0, namely:
	
	Attempt to import module: run_tests.py
	Can't find any of:
		tests/run_tests/py.py
		tests/run_tests/py.js
		/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.py
		/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.js
		/usr/local/bin/run_tests/py.py
		/usr/local/bin/run_tests/py.js
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.py
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.js
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.py
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.js
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.py
		/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.js
		/usr/local/lib/python3.7/site-packages/run_tests/py.py
		/usr/local/lib/python3.7/site-packages/run_tests/py.js
		/Data/Code/public/ioflo/run_tests/py.py
		/Data/Code/public/ioflo/run_tests/py.js
		/Data/Code/public/bottle/run_tests/py.py
		/Data/Code/public/bottle/run_tests/py.js
		/Data/Code/public/raet/run_tests/py.py
		/Data/Code/public/raet/run_tests/py.js
		/Data/Code/private/sentrific/sentroid/run_tests/py.py
		/Data/Code/private/sentrific/sentroid/run_tests/py.js
		/Data/Code/private/indigo/bluepea/src/run_tests/py.py
		/Data/Code/private/indigo/bluepea/src/run_tests/py.js
		/Data/Code/private/reputage/didery/src/run_tests/py.py
		/Data/Code/private/reputage/didery/src/run_tests/py.js



Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 5
npm ERR! didery@1.0.0 prep-tests: `transcrypt -b -de -v -n -p .none tests/run_tests.py && python -m clean_tests`
npm ERR! Exit status 5
npm ERR! 
npm ERR! Failed at the didery@1.0.0 prep-tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samuel/.npm/_logs/2018-09-26T13_06_30_700Z-debug.log
samuel@AiBook:/Data/Code/private/reputage/didery/src/didery/static/
sumes that the only python installed is python3. Should always used python3 not python in scripts.

**Comment by ntelfer** [comment]
> Looks like didery as$ npm run-script prep-tests
> 
> > didery@1.0.0 prep-tests /Data/Code/private/reputage/didery/src/didery/static
> > transcrypt -b -de -v -n -p .none tests/run_tests.py && python -m clean_tests
> 
> Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.7.5
> Copyright (C) Geatec Engineering. License: Apache 2.0
> 
> Parsing module: /usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/**runtime**.py
> Generating code for module: /Data/Code/private/reputage/didery/src/didery/static/tests/**target**/org.transcrypt.**runtime**.js
> Saving target code in: /Data/Code/private/reputage/didery/src/didery/static/tests/**target**/org.transcrypt.**runtime**.js
> 
> ```
> Exception of class <class 'org.transcrypt.utils.Error'> enhanced at:
>     file: /usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py
>     function: __init__
>     line: 91
>     context: ["                message = f'\\n\\t{exception}'\n"]
>     kwargs: {'message': "\n\tError while compiling (offending file last):\n\tFile '<org.transcrypt.compiler.Module object at 0x10c6d4630>', line 0, namely:\n\t\n\tAttempt to import module: run_tests.py\n\tCan't find any of:\n\t\ttests/run_tests/py.py\n\t\ttests/run_tests/py.js\n\t\t/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.py\n\t\t/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.js\n\t\t/usr/local/bin/run_tests/py.py\n\t\t/usr/local/bin/run_tests/py.js\n\t\t/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.py\n\t\t/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.js\n\t\t/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.py\n\t\t/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.js\n\t\t/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.py\n\t\t/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.js\n\t\t/usr/local/lib/python3.7/site-packages/run_tests/py.py\n\t\t/usr/local/lib/python3.7/site-packages/run_tests/py.js\n\t\t/Data/Code/public/ioflo/run_tests/py.py\n\t\t/Data/Code/public/ioflo/run_tests/py.js\n\t\t/Data/Code/public/bottle/run_tests/py.py\n\t\t/Data/Code/public/bottle/run_tests/py.js\n\t\t/Data/Code/public/raet/run_tests/py.py\n\t\t/Data/Code/public/raet/run_tests/py.js\n\t\t/Data/Code/private/sentrific/sentroid/run_tests/py.py\n\t\t/Data/Code/private/sentrific/sentroid/run_tests/py.js\n\t\t/Data/Code/private/indigo/bluepea/src/run_tests/py.py\n\t\t/Data/Code/private/indigo/bluepea/src/run_tests/py.js\n\t\t/Data/Code/private/reputage/didery/src/run_tests/py.py\n\t\t/Data/Code/private/reputage/didery/src/run_tests/py.js\n"}
>     result: Error while compiling (offending file last):
> File '<org.transcrypt.compiler.Module object at 0x10c6d4630>', line 0, namely:
> 
> Attempt to import module: run_tests.py
> Can't find any of:
> 	tests/run_tests/py.py
> 	tests/run_tests/py.js
> 	/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.py
> 	/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.js
> 	/usr/local/bin/run_tests/py.py
> 	/usr/local/bin/run_tests/py.js
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.py
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.js
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.py
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.js
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.py
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.js
> 	/usr/local/lib/python3.7/site-packages/run_tests/py.py
> 	/usr/local/lib/python3.7/site-packages/run_tests/py.js
> 	/Data/Code/public/ioflo/run_tests/py.py
> 	/Data/Code/public/ioflo/run_tests/py.js
> 	/Data/Code/public/bottle/run_tests/py.py
> 	/Data/Code/public/bottle/run_tests/py.js
> 	/Data/Code/public/raet/run_tests/py.py
> 	/Data/Code/public/raet/run_tests/py.js
> 	/Data/Code/private/sentrific/sentroid/run_tests/py.py
> 	/Data/Code/private/sentrific/sentroid/run_tests/py.js
> 	/Data/Code/private/indigo/bluepea/src/run_tests/py.py
> 	/Data/Code/private/indigo/bluepea/src/run_tests/py.js
> 	/Data/Code/private/reputage/didery/src/run_tests/py.py
> 	/Data/Code/private/reputage/didery/src/run_tests/py.js
> ```
> Error while compiling (offending file last):
> File '<org.transcrypt.compiler.Module object at 0x10c6d4630>', line 0, namely:
> 
> ```
> Attempt to import module: run_tests.py
> Can't find any of:
> 	tests/run_tests/py.py
> 	tests/run_tests/py.js
> 	/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.py
> 	/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.js
> 	/usr/local/bin/run_tests/py.py
> 	/usr/local/bin/run_tests/py.js
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.py
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.js
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.py
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.js
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.py
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.js
> 	/usr/local/lib/python3.7/site-packages/run_tests/py.py
> 	/usr/local/lib/python3.7/site-packages/run_tests/py.js
> 	/Data/Code/public/ioflo/run_tests/py.py
> 	/Data/Code/public/ioflo/run_tests/py.js
> 	/Data/Code/public/bottle/run_tests/py.py
> 	/Data/Code/public/bottle/run_tests/py.js
> 	/Data/Code/public/raet/run_tests/py.py
> 	/Data/Code/public/raet/run_tests/py.js
> 	/Data/Code/private/sentrific/sentroid/run_tests/py.py
> 	/Data/Code/private/sentrific/sentroid/run_tests/py.js
> 	/Data/Code/private/indigo/bluepea/src/run_tests/py.py
> 	/Data/Code/private/indigo/bluepea/src/run_tests/py.js
> 	/Data/Code/private/reputage/didery/src/run_tests/py.py
> 	/Data/Code/private/reputage/didery/src/run_tests/py.js
> ```
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/site-packages/transcrypt/**main**.py", line 157, in main
> compiler.Program (transpilationDirs, **symbols**, **envir**)
> File "/usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 91, in **init**
> message = f'\n\t{exception}'
> File "/usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 206, in enhanceException
> raise result
> File "/usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 87, in **init**
> self.provide (self.mainModuleName, '**main**')
> File "/usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 101, in provide
> return Module (self, moduleName, **moduleName**)
> File "/usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 116, in **init**
> self.findPaths ()
> File "/usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 256, in findPaths
> '\n\tCan't find any of:\n\t\t{}\n'.format ('\n\t\t'. join (searchedModulePaths))
> org.transcrypt.utils.Error: Error while compiling (offending file last):
> File '<org.transcrypt.compiler.Module object at 0x10c6d4630>', line 0, namely:
> 
> ```
> Attempt to import module: run_tests.py
> Can't find any of:
> 	tests/run_tests/py.py
> 	tests/run_tests/py.js
> 	/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.py
> 	/usr/local/lib/python3.7/site-packages/transcrypt/modules/run_tests/py.js
> 	/usr/local/bin/run_tests/py.py
> 	/usr/local/bin/run_tests/py.js
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.py
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip/run_tests/py.js
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.py
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/run_tests/py.js
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.py
> 	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/run_tests/py.js
> 	/usr/local/lib/python3.7/site-packages/run_tests/py.py
> 	/usr/local/lib/python3.7/site-packages/run_tests/py.js
> 	/Data/Code/public/ioflo/run_tests/py.py
> 	/Data/Code/public/ioflo/run_tests/py.js
> 	/Data/Code/public/bottle/run_tests/py.py
> 	/Data/Code/public/bottle/run_tests/py.js
> 	/Data/Code/public/raet/run_tests/py.py
> 	/Data/Code/public/raet/run_tests/py.js
> 	/Data/Code/private/sentrific/sentroid/run_tests/py.py
> 	/Data/Code/private/sentrific/sentroid/run_tests/py.js
> 	/Data/Code/private/indigo/bluepea/src/run_tests/py.py
> 	/Data/Code/private/indigo/bluepea/src/run_tests/py.js
> 	/Data/Code/private/reputage/didery/src/run_tests/py.py
> 	/Data/Code/private/reputage/didery/src/run_tests/py.js
> ```
> Aborted
> npm ERR! code ELIFECYCLE
> npm ERR! errno 5
> npm ERR! didery@1.0.0 prep-tests: `transcrypt -b -de -v -n -p .none tests/run_tests.py && python -m clean_tests`
> npm ERR! Exit status 5
> npm ERR!
> npm ERR! Failed at the didery@1.0.0 prep-tests script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/samuel/.npm/_logs/2018-09-26T13_06_30_700Z-debug.log
> samuel@AiBook:/Data/Code/private/reputage/didery/src/didery/static/
> sumes that the only python installed is python3. Should always used python3 not python in scripts.

This is caused by the version of transcrypt installed on your system.  transcrypt<=3.6.101 is required for it to work.  The setup.py file has been updated to reflect this dependency.
